In [56]:
import sys
sys.path.append("../src")

In [57]:
from data_loader import load_processed_dataset
from text_cleaning import preprocess

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kunja\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [58]:
df = load_processed_dataset(path="../data/processed/merged_news.csv")
df.shape

(38483, 3)

In [59]:
real_news = df[df["label"] == 1]
real_news

,title,text,label
4,Trump asks for probe into imports of foreign-m...,WASHINGTON (Reuters) - U.S. President Donald T...,1
5,Detained Venezuelan-U.S. Citgo executives to b...,WASHINGTON/CARACAS (Reuters) - Venezuelan Pres...,1
7,Russian foreign ministry says neither confirms...,MOSCOW (Reuters) - Russia’s Foreign Ministry d...,1
9,Iraq launches final offensive on Islamic State...,(Reuters) - Iraqi forces launched on Thursday ...,1
10,Kurds offer joint border deployment as Iraq th...,BAGHDAD (Reuters) - Iraq s Kurdish region said...,1
...,...,...,...
38477,Kurdish forces still control Khurmala oil fiel...,BAGHDAD (Reuters) - Kurdish forces have not wi...,1
38478,Russia ready to rebuild security ties with U.S...,MOSCOW (Reuters) - Russia is ready to resume c...,1
38479,Kremlin says ready to mediate North Korea-U.S....,MOSCOW (Reuters) - Russia is ready to act as a...,1
38481,"Factbox: Belgian mother of two, young New York...",(Reuters) - A New Jersey man who worked at the...,1
38482,Pregnant U.S. teenager moved to Iraq from Syri...,WASHINGTON (Reuters) - The Pentagon said on Tu...,1

In [60]:
import re
real_news["text"].apply(lambda x: re.sub(r"^[A-Za-z\s/,.]*\(Reuters\)\s*-\s*", "", x))

4        U.S. President Donald Trump on Thursday will s...
5        Venezuelan President Nicolas Maduro said on We...
7        Russia’s Foreign Ministry declined on Tuesday ...
9        Iraqi forces launched on Thursday an offensive...
10       Iraq s Kurdish region said on Thursday it had ...
                               ...
38477    Kurdish forces have not withdrawn from the Khu...
38478    Russia is ready to resume cooperation with the...
38479    Russia is ready to act as a mediator between N...
38481    A New Jersey man who worked at the World Trade...
38482    The Pentagon said on Tuesday that U.S. forces ...
Name: text, Length: 21191, dtype: str

In [61]:
def strip_reuters_prefix(text):
    """
    Removes the prefix from a text that matches the pattern of a Reuters news article.
    
    Args:
        text (str): The input text to process.
        
    Returns:
        str: The text with the Reuters prefix removed.
    """
    return re.sub(r"^[A-Za-z\s/,.]*\(Reuters\)\s*-\s*", "", text)

In [62]:
df["cleaned_text"] = df["text"].apply(strip_reuters_prefix)

In [63]:
df["word_count"] = df["text"].apply(lambda x: len(str(x).split()))
df["cleaned_word_count"] = df["cleaned_text"].apply(lambda x: len(str(x).split()))

In [64]:
df[df["word_count"] != df["cleaned_word_count"]][["text", "cleaned_text", "word_count", "cleaned_word_count"]]

,text,cleaned_text,word_count,cleaned_word_count
4,WASHINGTON (Reuters) - U.S. President Donald T...,U.S. President Donald Trump on Thursday will s...,265,262
5,WASHINGTON/CARACAS (Reuters) - Venezuelan Pres...,Venezuelan President Nicolas Maduro said on We...,627,624
7,MOSCOW (Reuters) - Russia’s Foreign Ministry d...,Russia’s Foreign Ministry declined on Tuesday ...,242,239
9,(Reuters) - Iraqi forces launched on Thursday ...,Iraqi forces launched on Thursday an offensive...,310,308
10,BAGHDAD (Reuters) - Iraq s Kurdish region said...,Iraq s Kurdish region said on Thursday it had ...,642,639
...,...,...,...,...
38477,BAGHDAD (Reuters) - Kurdish forces have not wi...,Kurdish forces have not withdrawn from the Khu...,70,67
38478,MOSCOW (Reuters) - Russia is ready to resume c...,Russia is ready to resume cooperation with the...,405,402
38479,MOSCOW (Reuters) - Russia is ready to act as a...,Russia is ready to act as a mediator between N...,246,243
38481,(Reuters) - A New Jersey man who worked at the...,A New Jersey man who worked at the World Trade...,416,414
38482,WASHINGTON (Reuters) - The Pentagon said on Tu...,The Pentagon said on Tuesday that U.S. forces ...,185,182

In [65]:
df.drop(columns=["word_count", "cleaned_word_count"], inplace=True)

In [66]:
fake_news = df[df["label"] == 0]

In [67]:
fake_news

,title,text,label,cleaned_text
0,TOP 10 TWEETS From Democrat Debate,"Here s the fake black guy, Shaun King weighing...",0,"Here s the fake black guy, Shaun King weighing..."
1,Incredible Photo Of North Korean Soldier Secr...,While Trump s Secretary of State was visiting ...,0,While Trump s Secretary of State was visiting ...
2,Patrick Henningsen LIVE with guest Sean Stone ...,Join Patrick every week here at 21WIRE.TV for ...,0,Join Patrick every week here at 21WIRE.TV for ...
3,Trump Just Bragged About The Size Of His Hand...,The size of Donald Trump s hands seems to be a...,0,The size of Donald Trump s hands seems to be a...
6,Lindsey Graham Calls Out His Own Party; Says ...,S.C. Senator Lindsey Graham has been a shining...,0,S.C. Senator Lindsey Graham has been a shining...
...,...,...,...,...
38466,RNC Creates Obstructionist Force To Stop Obam...,Before Supreme Court Justice Scalia s body was...,0,Before Supreme Court Justice Scalia s body was...
38469,CLASSLESS HOLLYWOOD LIB ADDRESSES THOUSANDS AT...,Just another whiny radical leftist keeping it ...,0,Just another whiny radical leftist keeping it ...
38475,Republicans Are Trying To Destroy The Senate ...,"The American Legislative Exchange Council, oth...",0,"The American Legislative Exchange Council, oth..."
38476,WILL WHAT THIS NFL OWNER Just Threatened To Do...,Cowboys owner Jerry Jones just threatened to s...,0,Cowboys owner Jerry Jones just threatened to s...
38480,Lake Oroville Dam Spillway Damage Results in E...,21st Century Wire says The Oroville dam in Nor...,0,21st Century Wire says The Oroville dam in Nor...

In [68]:
fake_news[fake_news['text'].str.contains('featured image|getty')]

,title,text,label,cleaned_text
3990,"Numbskull Republican Ignores History, Says Re...",Republican Rep. Ted Poe (R-Texas) spoke with F...,0,Republican Rep. Ted Poe (R-Texas) spoke with F...
7417,What This Georgia Republican Just Said About ...,A state Republican in Georgia made an astonish...,0,A state Republican in Georgia made an astonish...
7962,"Donald Trump Attacked Stephen Colbert, So Col...","In an interview with TIME, Donald Trump puss...",0,"In an interview with TIME, Donald Trump puss..."
8421,Chris Wallace Just Shoved His Foot So Far Up ...,Donald Trump may spend his time furiously twee...,0,Donald Trump may spend his time furiously twee...
9394,The Bundy Militia Now Has An ISIS Supporter H...,David Fry is a self-titled computer expert t...,0,David Fry is a self-titled computer expert t...
9632,Trump Just Promised To Only Pick A White Man ...,"According to Donald Trump, Joe The Plumber was...",0,"According to Donald Trump, Joe The Plumber was..."
10042,Guess What UK Political Leaders Really Think ...,The British Parliament conducted what can only...,0,The British Parliament conducted what can only...
10462,Trump Stooge Nunes Just Gave the Most Immatur...,"Trump transition team member Devin Nunes, who ...",0,"Trump transition team member Devin Nunes, who ..."
10757,Concerned Adult Literally Pays Young Black Ki...,An unknown man saw some children playing on th...,0,An unknown man saw some children playing on th...
10825,Rachel Maddow CRUSHES The GOP Fantasy That Re...,Republicans have revived an old and overused p...,0,Republicans have revived an old and overused p...
11140,"Instead Of Tip, ‘Christian’ Trump Supporter L...",Donald Trump is a disease. The symptoms have a...,0,Donald Trump is a disease. The symptoms have a...
14791,POLL: Most Trump Supporters Say Fake ‘Bowling...,Did you know that people who support Donald Tr...,0,Did you know that people who support Donald Tr...
14985,Mike Pence Saw ‘DO NOT TOUCH’ On Critical NAS...,We already knew Vice President Mike Pence does...,0,We already knew Vice President Mike Pence does...
16155,Secret Service Agent Risks Everything To Deno...,Would you die to save the President? What if i...,0,Would you die to save the President? What if i...
17156,MIC DROP: Watch Neil deGrasse Tyson SHRED Fla...,Rapper B.o.B. has recently gained some notorie...,0,Rapper B.o.B. has recently gained some notorie...
18829,Fox News Attacks Obama’s National Cancer Init...,President Obama gave America a bit of the spir...,0,President Obama gave America a bit of the spir...
20213,Trump Gives Press Credentials To A Racist Blo...,Gateway Pundit is a popular publication among ...,0,Gateway Pundit is a popular publication among ...
21026,BOMBSHELL: Israeli Spies Reveal Trump’s Pee P...,Donald Trump may be decrying the documents dum...,0,Donald Trump may be decrying the documents dum...
21616,What Facebook Just Did About Guns Is Going To...,Facebook announced that it will be banning its...,0,Facebook announced that it will be banning its...
24067,Facebook Founder Tells Trump to go F*ck Himse...,"Donald Trump is horrible, and Facebook founder...",0,"Donald Trump is horrible, and Facebook founder..."
25452,Trump Gets Smacked Down After His Immensely S...,"Last year, in an effort to demonize Hillary Cl...",0,"Last year, in an effort to demonize Hillary Cl..."
25798,"White Security Guard Shoots Himself, Blames N...",On Tuesday night St. Catherine University secu...,0,On Tuesday night St. Catherine University secu...
26391,Hackers Reveal Trump Linked The Most Powerful...,Donald Trump s administration is already provi...,0,Donald Trump s administration is already provi...
27886,Betsy DeVos Gets WRECKED After Praising Segre...,Donald Trump s education secretary proved she ...,0,Donald Trump s education secretary proved she ...
28539,Seizure Victim 2nd Amendmented A Fireman Who ...,Greg Pruitt s wife was awoken at approximately...,0,Greg Pruitt s wife was awoken at approximately...
29704,Trump Supporter Threatens To Slaughter Black ...,Ever since Officer Darren Wilson murdered unar...,0,Ever since Officer Darren Wilson murdered unar...
30142,Trump’s Puerto Rico Contract With Two-Man Ene...,When the Trump administration hired a tiny two...,0,When the Trump administration hired a tiny two...
30864,Trump Tweets His Dumbest ‘Sweden’ Garbage Yet...,I m sorry I lied. Those four magic words wou...,0,I m sorry I lied. Those four magic words wou...
32476,The Academy Just Showed The GOP How Diversity...,The Academy Of Motion Picture Arts And Science...,0,The Academy Of Motion Picture Arts And Science...
32585,WATCH: Mike Pence Went To See ‘Hamilton’ And ...,Mike Pence took time off from organizing Trump...,0,Mike Pence took time off from organizing Trump...
34960,The Lying B**tard Behind The Fake Planned Par...,"David Daleiden, the mastermind behind the debu...",0,"David Daleiden, the mastermind behind the debu..."
35719,Trump Stole An Idea From North Korean Propaga...,Jesus f*cking Christ our President* is a moron...,0,Jesus f*cking Christ our President* is a moron...
36113,That Moment Conservative Star Milo Yiannopoul...,"If you have not yet heard, alt-Right (that mea...",0,"If you have not yet heard, alt-Right (that mea..."
36357,President Obama Is Putting An End To Inhumane...,President Obama announced via an op-ed in the ...,0,President Obama announced via an op-ed in the ...
36842,Jordanian Airline Tells Trump To F*ck Himself...,The Royal Jordanian airline is celebrating Don...,0,The Royal Jordanian airline is celebrating Don...
36943,Breitbart Racist Is Attacking Neil Degrasse T...,"Let s face it, Republicans hate Neil Degrasse ...",0,"Let s face it, Republicans hate Neil Degrasse ..."
37372,Trump Official Accidentally Leaks Plan To Ste...,Mexican President Enrique Pe a Nieto may not b...,0,Mexican President Enrique Pe a Nieto may not b...

In [69]:
fake_news.shape

(17292, 4)

In [70]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")

def clean_text_heavy(text):
    """
    Cleans the input text by removing stopwords, punctuation, numbers,
    and converting to lowercase. Intended for TF-IDF / classical ML models.

    Args:
        text (str): The input text to clean.

    Returns:
        str: The cleaned text.
    """
    # Convert to lowercase
    text = text.lower()

    # Remove punctuation and numbers (keep only letters and whitespace)
    text = re.sub(r'[^a-z\s]', '', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    # Remove stopwords
    stop_words = set(stopwords.words("english"))
    words = text.split()
    words = [word for word in words if word not in stop_words]

    # Join the words back into a string
    cleaned_text = " ".join(words)

    return cleaned_text

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kunja\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [71]:
def clean_text_light(text):
    """
    Cleans the input text by removing extra whitespaces
    and converting to lowercase. Intended for deep learning models.

    Args:
        text (str): The input text to clean.

    Returns:
        str: The cleaned text.
    """
    # Convert to lowercase
    text = text.lower()

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [72]:
df.drop(columns=["text"], inplace=True)

In [73]:
df["text_idf"] = df["cleaned_text"].apply(lambda x: preprocess(x, mode="heavy"))
df["distilbert_text"] = df["cleaned_text"].apply(lambda x: preprocess(x, mode="light"))

In [74]:
df.head()

,title,label,cleaned_text,text_idf,distilbert_text
0,TOP 10 TWEETS From Democrat Debate,0,"Here s the fake black guy, Shaun King weighing...",fake black guy shaun king weighing awesome ber...,"here s the fake black guy, shaun king weighing..."
1,Incredible Photo Of North Korean Soldier Secr...,0,While Trump s Secretary of State was visiting ...,trump secretary state visiting un base border ...,while trump s secretary of state was visiting ...
2,Patrick Henningsen LIVE with guest Sean Stone ...,0,Join Patrick every week here at 21WIRE.TV for ...,join patrick every week wiretv news views anal...,join patrick every week here at 21wire.tv for ...
3,Trump Just Bragged About The Size Of His Hand...,0,The size of Donald Trump s hands seems to be a...,size donald trump hands seems issue even socal...,the size of donald trump s hands seems to be a...
4,Trump asks for probe into imports of foreign-m...,1,U.S. President Donald Trump on Thursday will s...,us president donald trump thursday sign direct...,u.s. president donald trump on thursday will s...

In [75]:
df.to_csv("../data/processed/cleaned_news.csv", index=False)